### PR TITLE
better rainbow function

### PR DESCRIPTION
**Pull request by Jackojc**
cleaner and more readable rainbow function.

### CODE REVIEW

**Comment by Jackojc** [comment]
Addresses #17

**Comment by Jackojc** [comment]
Close #17

**Comment by Jackojc** [comment]
@Repertoi-e I thought you said I could close issues like this?

**Comment by Repertoi-e** [comment]
I think it has to be in the title of the PR or a commit.

**Comment by Jackojc** [comment]
I see, might try it with a later commit.

**Pull request merged**
